from django.urls import path
from dashboard.views.event_views import (
    event_list, event_create, event_detail, event_update, event_delete,
    category_list, category_create, category_detail, category_update, category_delete,
    payment_method_list, payment_method_create, payment_method_detail, payment_method_update, payment_method_delete,
    registration_list, registration_detail, registration_approve, registration_reject,
    event_statistics, survey_list, survey_create, survey_detail, survey_update, survey_delete, survey_duplicate, survey_questions, question_options, survey_results, survey_export, send_surveys,
)

urlpatterns = [
    path("eventos/", event_list, name="event_list"),
    path("eventos/crear/", event_create, name="event_create"),
    path("eventos/<int:pk>/", event_detail, name="event_detail"),
    path("eventos/<int:pk>/editar/", event_update, name="event_update"),
    path("eventos/<int:pk>/eliminar/", event_delete, name="event_delete"),
    path("categorias-eventos/", category_list, name="event_category_list"),
    path("categorias-eventos/crear/", category_create,
         name="event_category_create"),
    path("categorias-eventos/<int:pk>/",
         category_detail, name="event_category_detail"),
    path("categorias-eventos/<int:pk>/editar/",
         category_update, name="event_category_update"),
    path("categorias-eventos/<int:pk>/eliminar/",
         category_delete, name="event_category_delete"),
    path("metodos-pago/", payment_method_list, name="payment_method_list"),
    path("metodos-pago/crear/", payment_method_create,
         name="payment_method_create"),
    path("metodos-pago/<int:pk>/", payment_method_detail,
         name="payment_method_detail"),
    path("metodos-pago/<int:pk>/editar/",
         payment_method_update, name="payment_method_update"),
    path("metodos-pago/<int:pk>/eliminar/",
         payment_method_delete, name="payment_method_delete"),
    path("inscripciones/", registration_list, name="registration_list"),
    path("inscripciones/<int:pk>/", registration_detail,
         name="registration_detail"),
    path("inscripciones/<int:pk>/aprobar/",
         registration_approve, name="registration_approve"),
    path("inscripciones/<int:pk>/rechazar/",
         registration_reject, name="registration_reject"),
    path("estadisticas-eventos/", event_statistics, name="statistics"),
    path("encuestas/", survey_list, name="survey_list"),
    path("encuestas/crear/", survey_create, name="survey_create"),
    path("encuestas/<int:pk>/", survey_detail, name="survey_detail"),
    path("encuestas/<int:pk>/editar/", survey_update, name="survey_update"),
    path("encuestas/<int:pk>/eliminar/", survey_delete, name="survey_delete"),
    path("encuestas/<int:pk>/duplicar/",
         survey_duplicate, name="survey_duplicate"),
    path("encuestas/<int:pk>/preguntas/",
         survey_questions, name="survey_questions"),
    path("preguntas/<int:question_pk>/opciones/",
         question_options, name="question_options"),
    path("encuestas/<int:pk>/resultados/",
         survey_results, name="survey_results"),
    path("encuestas/<int:pk>/exportar/", survey_export, name="survey_export"),
    path("eventos/<int:event_pk>/enviar-encuestas/",
         send_surveys, name="send_surveys"),
]
